version: "3.3"
services:

    server:
      image: kkarczmarczyk/node-yarn:8.0
      container_name: server
      working_dir: /app
      command: bash -c "yarn && yarn start"
      volumes:
        - .:/app
      ports:
        - "3000:3000"

    builder:
      image: kkarczmarczyk/node-yarn:8.0
      container_name: builder
      working_dir: /app
      command: bash -c "yarn && yarn build"
      volumes:
        - .:/app
